development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kit_development
  pool: 5
  username: kitdev
  password: kitdev

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kit_test
  pool: 5
  username: kitdev
  password: kitdev

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kit_production
  pool: 5
  username: <%= ENV['KIT_DB_USER'] %>
  password: <%= ENV['KIT_DB_PASS'] %>
